server:
  port: 8080

#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/./user-sample
#    username: sa
#    password: 1
#    driver-class-name: org.h2.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true
#        use_sql_comments: true
#        default_batch_fetch_size: 100
#        show_sql: true
#
#  devtools:
#    livereload:
#      enabled: false

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

